### ISSUE TITLE
bundling issue, react-native 0.59.8

### ISSUE THREAD

**Issue by subhamchatterjee** [dsznajder/react-native-otp-inputs#57]
error: bundling failed: Error: Cannot combine flow and typescript plugins.
    at validatePlugins (/Work/node_modules/@babel/parser/lib/index.js:6084:11)
    at getParser (/Work/node_modules/@babel/parser/lib/index.js:11262:5)
    at parse (/Work/node_modules/@babel/parser/lib/index.js:11232:22)
    at parser (/Work/node_modules/@babel/core/lib/transformation/normalize-file.js:170:34)
    at normalizeFile (/Work/node_modules/@babel/core/lib/transformation/normalize-file.js:138:11)
    at runSync (/Work/node_modules/@babel/core/lib/transformation/index.js:44:43)
    at transformSync (/Work/node_modules/@babel/core/lib/transform.js:43:38)
    at Object.transform (/Work/node_modules/metro-react-native-babel-transformer/src/index.js:202:20)

**package.json**
"react": "16.8.3", "react-native": "0.59.8", "react-native-otp-inputs": "^3.2.0", "babel-preset-react-native": "^5.0.2", "metro-react-native-babel-preset": "^0.54.1"

**Comment by dsznajder** [comment]
@subhamchatterjee Why you use `babel-preset-react-native` together with `metro`? I'm pretty sure that this is main reason of this problem

**Comment by dsznajder** [comment]
@subhamchatterjee I'm closing it as i did not receive any further information from you so I assume this works fine :)
